variable "azure_app_id" {}
variable "azure_directory_id" {}
variable "azure_app_key" {}
variable "azure_subscription_id" {}
variable "azure_account_name" {}
variable "aws_account_name" {}
variable "gcp_account_name" {}
variable "gcp_project_id" {}
variable "gcp_project_creds_path" {}
variable "bootstrap_remote_state" {}